language: node_js

node_js:
  - "stable"

script:
  - npm run coverage

before_script:
  - npm install -g gulp-cli bower
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
